---
- name: Allow for distro source change / upgrade
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "apt-get update  --allow-releaseinfo-change"
  register: release_info_changed
  changed_when: release_info_changed.rc == 0
  tags: [ 'apt', 'release-info-change' ]
  when:
    - devconfig_try_upgrade|bool

- name: Update apt cache and do dist-upgrade
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    upgrade: full
  tags: [ 'apt', 'cache' ]
  when:
    - devconfig_try_upgrade|bool

- name: Reboot system to make the new kernel and modules take effect
  become: yes
  become_method: sudo
  reboot:
  when:
    - devconfig_try_upgrade|bool

- name: Install our generic dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - grub2
      - nvme-cli
      - ssh
      - bison
      - flex
      - libelf-dev
      - libncurses-dev
      - screen
      - git
      - e2fsprogs
      - xfsprogs
      - btrfs-progs
      - lvm2
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - libtool
      - psmisc
      - sed
      - vim
      - fio
      - libaio-dev
      - snmpd
      - snmp
      - trace-cmd
      - perf
    state: present
    update_cache: yes
  tags: [ 'kdevops', 'deps' ]
  when:
    - devconfig_try_install_kdevtools|bool

- name: Set up snmp
  become: yes
  become_method: sudo
  template:
    src: snmpd.conf
    dest: /etc/snmp/snmpd.conf
  when:
    - devconfig_try_install_kdevtools|bool
  tags: snmpd

- name: Enable snmpd service
  become: yes
  become_method: sudo
  systemd:
    name: snmpd
    enabled: yes
    masked: no
  tags: snmpd
  when:
    - devconfig_try_install_kdevtools|bool

- name: Start snmpd service
  become: yes
  become_method: sudo
  systemd:
    name: snmpd
    state: restarted
  tags: snmpd
  when:
    - devconfig_try_install_kdevtools|bool

- name: Install and sets up kdump
  become: yes
  become_method: sudo
  apt:
    name:
      - kdump-tools
  when:
    - devconfig_try_install_kdevtools|bool
  tags: kdump

- name: Install systemd-journal-remote
  become: yes
  become_method: sudo
  apt:
    name:
      - systemd-journal-remote
    update_cache: yes
  when:
    - devconfig_enable_systemd_journal_remote|bool
  tags: journal

- name: Install systemd-timesyncd
  become: yes
  become_method: sudo
  apt:
    name:
      - systemd-timesyncd
  when:
    - devconfig_enable_systemd_timesyncd|bool
  tags: timesyncd
