---
- name: Install pynfs build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - gcc
      - git-core
      - make
      - libkrb5-dev
      - python3-dev
      - swig
      - python3-gssapi
      - python3-ply
      - python3-standard-xdr-lib
    state: present
    update_cache: yes
  tags: [ 'pynfs', 'deps' ]
