---
- name: Get OS-specific variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
        - default.yml
      paths:
        - 'vars'

- name: Determine which fsprogs package is needed for "{{ nfsd_export_fstype }}"
  set_fact:
    fsprogs: "{{ fstype_userspace_progs[nfsd_export_fstype] | default() }}"

- name: Add {{ fsprogs }} to the nfsd packages list
  set_fact:
    nfsd_packages: "{{ nfsd_packages + [fsprogs] }}"
  when:
    - fsprogs is defined
    - fsprogs

- name: Install nfsd dependencies
  become: yes
  become_method: sudo
  yum:
    update_cache: yes
    name: "{{ nfsd_packages }}"
  retries: 3
  delay: 5
  register: result
  until: result.rc == 0
