---
- name: Import optional extra_args file
  include_vars: "{{ item }}"
  ignore_errors: yes
  with_first_found:
    - files:
      - "../extra_vars.yml"
      - "../extra_vars.yaml"
      - "../extra_vars.json"
      skip: true
  tags: vars

# Distro specific
- name: Install dependencies
  include_tasks:
    file: install-deps/main.yml

# We do this regardless of what distro you use
- name: Install b4
  become: yes
  become_method: sudo
  pip:
    name:
      - b4
  when:
    - target_linux_install_b4 is defined
    - target_linux_install_b4
    - ansible_facts['os_family']|lower != 'debian'
  tags: linux

- name: Install b4 on host
  become: yes
  become_method: sudo
  pip:
    name:
      - b4
  when:
    - target_linux_install_b4 is defined
    - target_linux_install_b4
    - bootlinux_9p|bool
    - ansible_facts['os_family']|lower != 'debian'
  tags: linux
  run_once: true
  delegate_to: localhost

- name: Get username we are using
  command:
    cmd: whoami
  register: username_on_target
  when:
    - infer_uid_and_group|bool

- name: Set target user as a fact
  set_fact:
    target_user: "{{ username_on_target.stdout }}"
  when:
    - infer_uid_and_group|bool

- name: Set bootlinux_b4_am_this_host as a fact for dev hosts only
  set_fact:
    bootlinux_b4_am_this_host: "{{ ansible_hostname | regex_search('^.*-dev$') is not none }}"
  when:
    - kdevops_baseline_and_dev|bool

- name: Enable b4 am all hosts if not deploying dev and baseline nodes
  set_fact:
    bootlinux_b4_am_this_host: True
  when:
    - not kdevops_baseline_and_dev|bool

- name: Run getent against the inferred target user
  getent:
    database: passwd
    key: "{{ target_user }}"
  register: getent_running_user
  when:
    - infer_uid_and_group|bool

- name: Run getent against the inferred target group
  getent:
    database: group
    key: "{{ target_user }}"
  register: getent_on_group
  when:
    - infer_uid_and_group|bool

- name: Override user and group with inferred settings if feature is enabled
  set_fact:
    user: "hplip"
    data_user: "{{ target_user }}"
    data_group: "{{ ((getent_on_group.values() | first).values() | first).keys() | first }}"
  when:
    - infer_uid_and_group|bool

- name: Create {{ data_path }} partition if not created yet
  include_role:
    name: create_partition
  vars:
    disk_setup_device: "{{ data_device }}"
    disk_setup_fstype: "{{ data_fstype }}"
    disk_setup_label: "{{ data_label }}"
    disk_setup_fs_opts: "{{ data_fs_opts }}"
    disk_setup_path: "{{ data_path }}"
    disk_setup_user: "{{ data_user }}"
    disk_setup_group: "{{ data_group }}"
  tags: [ 'data_partition' ]

# Distro agnostic stuff to build and boot Linux goes below

- name: Mount bootlinux 9p and add to fstab if it does not exist
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  mount:
    name: "{{ target_linux_dir_path }}"
    src: "{{ bootlinux_9p_mount_tag }}"
    fstype: "9p"
    opts: "ro,trans=virtio,version=9p2000.L,posixacl,cache=none"
    state: "mounted"
  tags: [ 'data_partition' ]
  when:
    - bootlinux_9p|bool

- name: Copy kernel delta if requested on the client side
  template:
    src: "{{ target_linux_extra_patch }}"
    dest: "{{ target_linux_dir_path }}/{{ target_linux_extra_patch }}"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    mode: 0644
  tags: [ 'linux', 'git', 'config' ]
  when:
    - not bootlinux_9p|bool
    - target_linux_extra_patch is defined

- name: Copy kernel delta if requested on the host side
  template:
    src: "{{ target_linux_extra_patch }}"
    dest: "{{ bootlinux_9p_host_path }}/{{ target_linux_extra_patch }}"
    owner: "{{ data_user }}"
  tags: [ 'linux', 'git', 'config' ]
  when:
    - bootlinux_9p|bool
    - target_linux_extra_patch is defined

- name: git clone {{ target_linux_tree }} on the client side
  git:
    repo: "{{ target_linux_git }}"
    dest: "{{ target_linux_dir_path }}"
    update: yes
    depth: "{{ target_linux_shallow_depth }}"
    version: "{{ target_linux_tag }}"
  retries: 3
  delay: 5
  register: result
  until: not result.failed
  tags: [ 'linux', 'git', 'clone']
  when:
    - not bootlinux_9p|bool

- name: git clone {{ target_linux_tree }} on the host side
  git:
    repo: "{{ target_linux_git }}"
    dest: "{{ bootlinux_9p_host_path }}"
    update: yes
    depth: "{{ target_linux_shallow_depth }}"
    version: "{{ target_linux_tag }}"
  retries: 3
  delay: 5
  register: result
  until: not result.failed
  tags: [ 'linux', 'git', 'clone']
  when:
    - bootlinux_9p|bool
  run_once: true
  delegate_to: localhost

- name: Copy kernel delta if requested on the client side
  template:
    src: "{{ target_linux_extra_patch }}"
    dest: "{{ target_linux_dir_path }}/{{ target_linux_extra_patch }}"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    mode: 0644
  tags: [ 'linux', 'git', 'config' ]
  when:
    - not bootlinux_9p|bool
    - target_linux_extra_patch is defined

- name: Copy kernel delta if requested on the host side
  template:
    src: "{{ target_linux_extra_patch }}"
    dest: "{{ bootlinux_9p_host_path }}/{{ target_linux_extra_patch }}"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    mode: 0644
  tags: [ 'linux', 'git', 'config' ]
  when:
    - bootlinux_9p|bool
    - target_linux_extra_patch is defined
  run_once: true
  delegate_to: localhost

- name: Apply kernel delta if requested on the client side
  command: "git am {{ target_linux_extra_patch }}"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'git', 'extra-patch', 'skip_ansible_lint' ]
  when:
    - not bootlinux_9p|bool
    - target_linux_extra_patch is defined

- name: Apply kernel delta if requested on the host side
  command: "git am {{ target_linux_extra_patch }}"
  args:
    chdir: "{{ bootlinux_9p_host_path }}"
  tags: [ 'linux', 'git', 'extra-patch', 'skip_ansible_lint' ]
  when:
    - bootlinux_9p|bool
    - target_linux_extra_patch is defined
  run_once: true
  delegate_to: localhost

- name: Set git user name and email if needed
  shell: |
    if ! $(git config --get user.email) ; then
      git config --global user.email user@example.com
    fi
    if ! $(git config --get user.name) ; then
      git config --global user.name user
    fi
  tags: [ 'linux', 'git', 'extra-patch', 'skip_ansible_lint' ]
  when:
    - target_linux_apply_patch_message_id is defined
    - target_linux_apply_patch_message_id | length > 0
    - bootlinux_b4_am_this_host|bool

- name: Variable values
  debug:
    msg: "{{ target_linux_apply_patch_message_id }}"
  when:
    - target_linux_apply_patch_message_id is defined

- name: Apply message patch set if requested on the client side
  shell: b4 am -o - {{target_linux_apply_patch_message_id}} | git am
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'extra-patch', 'skip_ansible_lint' ]
  when:
    - not bootlinux_9p|bool
    - target_linux_apply_patch_message_id is defined
    - target_linux_apply_patch_message_id | length > 0
    - bootlinux_b4_am_this_host|bool

- name: Apply message patch set if requested on the host side
  shell: b4 am -o - {{target_linux_apply_patch_message_id}} | git am
  args:
    chdir: "{{ bootlinux_9p_host_path }}"
  tags: [ 'linux', 'extra-patch', 'skip_ansible_lint' ]
  when:
    - bootlinux_9p|bool
    - target_linux_apply_patch_message_id is defined
    - target_linux_apply_patch_message_id | length > 0
    - bootlinux_b4_am_this_host|bool
  run_once: true
  delegate_to: localhost

- name: Check whether config-kdevops exists
  stat:
    path: "{{ role_path }}/templates/config-kdevops"
  register: config_kdevops
  delegate_to: localhost

- name: Found config-kdevops, using it for template
  set_fact:
    linux_config: "config-kdevops"
  when: config_kdevops.stat.exists

- name: No config-kdevops, looking for {{ target_linux_config }}
  set_fact:
    linux_config: "{{ target_linux_config }}"
  when: not config_kdevops.stat.exists

- name: Copy configuration for Linux {{ target_linux_tree }} on the client side
  template:
    src: "{{ linux_config }}"
    dest: "{{ target_linux_dir_path }}/.config"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    mode: 0644
  tags: [ 'linux', 'git', 'config' ]
  when:
    - not bootlinux_9p|bool

- name: Copy configuration for Linux {{ target_linux_tree }} on the host side
  template:
    src: "{{ linux_config }}"
    dest: "{{ bootlinux_9p_host_path }}/.config"
    mode: 0644
  tags: [ 'linux', 'git', 'config' ]
  when:
    - bootlinux_9p|bool
  run_once: true
  delegate_to: localhost

- name: Set kernel localversion if requested on the client side
  shell: "echo {{ target_linux_localversion }} > {{ target_linux_dir_path }}/localversion"
  tags: [ 'linux', 'git', 'config' ]
  when:
    - not bootlinux_9p|bool
    - target_linux_localversion is defined

- name: Set kernel localversion if requested on the host side
  shell: "echo {{ target_linux_localversion }} > {{ bootlinux_9p_host_path }}/localversion"
  tags: [ 'linux', 'git', 'config' ]
  when:
    - bootlinux_9p|bool
    - target_linux_localversion is defined
  run_once: true
  delegate_to: localhost

- name: Configure Linux {{ target_linux_tree }} on the client side
  shell: |
    set -o pipefail
    yes "" | make oldconfig
  register: configure_done
  changed_when: configure_done.rc == 0 or configure_done.rc == 141
  failed_when: configure_done.rc != 0 and configure_done.rc != 141
  args:
    chdir: "{{ target_linux_dir_path }}"
    executable: /bin/bash
  tags: [ 'linux', 'oldconfig' ]
  when:
    - not bootlinux_9p|bool

- name: Configure Linux {{ target_linux_tree }} on the host side
  shell: |
    set -o pipefail
    yes "" | make oldconfig
  register: configure_done
  changed_when: configure_done.rc == 0 or configure_done.rc == 141
  failed_when: configure_done.rc != 0 and configure_done.rc != 141
  args:
    chdir: "{{ bootlinux_9p_host_path }}"
    executable: /bin/bash
  tags: [ 'linux', 'oldconfig' ]
  when:
    - bootlinux_9p|bool
  run_once: true
  delegate_to: localhost

- name: Build {{ target_linux_tree }} on the client side
  command: "{{ target_linux_make_cmd }}"
  register: build
  changed_when: "build.rc == 0"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'build-linux' ]
  when:
    - not bootlinux_9p|bool

- name: Build {{ target_linux_tree }} cxl_test on the client side
  command: "{{ target_linux_make_cmd }} M=tools/testing/cxl"
  register: build_cxl_test
  changed_when: "build_cxl_test.rc == 0"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'build-linux', 'cxl-build' ]
  when:
    - not bootlinux_9p|bool
    - bootlinux_cxl_test|bool

- name: See if snake-oil cert file is present on client
  stat:
    path: "{{ target_linux_dir_path }}/certs/signing_key.pem"
  register: snaik_oil_file
  tags: [ 'linux', 'build-linux' ]
  when:
    - not bootlinux_9p|bool

- name: Ensure we allow world to read the snake oil in case of NFS or 9p read only usage
  file:
    path: "{{ target_linux_dir_path }}/certs/signing_key.pem"
    mode: "0755"
  tags: [ 'linux', 'build-linux' ]
  when:
    - not bootlinux_9p|bool
    - snaik_oil_file.stat.exists

- name: Get nproc on the host side
  command: "{{ num_jobs }}"
  tags: [ 'linux', 'build-linux', 'configure', 'cxl-build' ]
  register: nproc_9p
  when:
    - bootlinux_9p|bool
  run_once: true
  delegate_to: localhost

- name: Build {{ target_linux_tree }} on the host side using {{ nproc_9p.stdout }} threads
  make:
    jobs: "{{ nproc_9p.stdout }}"
    chdir: "{{ bootlinux_9p_host_path }}"
  tags: [ 'linux', 'build-linux' ]
  when:
    - bootlinux_9p|bool
  run_once: true
  delegate_to: localhost

- name: Build {{ target_linux_tree }} cxl_test on the host side using {{ nproc_9p.stdout }} threads
  make:
    jobs: "{{ nproc_9p.stdout }}"
    chdir: "{{ bootlinux_9p_host_path }}"
    params:
      M: "tools/testing/cxl"
  tags: [ 'linux', 'build-linux', 'cxl-build' ]
  when:
    - bootlinux_9p|bool
    - bootlinux_cxl_test|bool
  run_once: true
  delegate_to: localhost

- name: See if snake-oil cert file is present on host
  stat:
    path: "{{ bootlinux_9p_host_path }}/certs/signing_key.pem"
  register: snaik_oil_file_9p
  tags: [ 'linux', 'build-linux' ]
  when:
    - bootlinux_9p|bool
  run_once: true
  delegate_to: localhost

- name: Ensure we allow world to read the snake oil in case of NFS or 9p read only usage
  file:
    path: "{{ bootlinux_9p_host_path }}/certs/signing_key.pem"
    mode: "0755"
  tags: [ 'linux', 'build-linux' ]
  when:
    - bootlinux_9p|bool
    - snaik_oil_file_9p.stat.exists
  run_once: true
  delegate_to: localhost

# Say you want to remove a kernel you no longer care for:
# ansible-playbook -i hosts --tags uninstall-linux --extra-vars "uninstall_kernel_ver=4.19.58" bootlinux.yml
- name: Uninstall an old version of Linux manually specified
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  file:
    state: absent
    path: "{{ item }}"
  tags: [ 'linux', 'uninstall-linux' ]
  with_items:
    - "/boot/vmlinuz-{{ uninstall_kernel_ver }}"
    - "/boot/vmlinuz-{{ uninstall_kernel_ver }}.old"
    - "/boot/initrd.img-{{ uninstall_kernel_ver }}"
    - "/boot/initrd.img-{{ uninstall_kernel_ver }}.old"
    - "/boot/config-{{ uninstall_kernel_ver }}"
    - "/boot/config-{{ uninstall_kernel_ver }}.old"
    - "/boot/System.map-{{ uninstall_kernel_ver }}"
    - "/boot/System.map-{{ uninstall_kernel_ver }}.old"
    - "/lib/modules/{{ uninstall_kernel_ver }}"
  loop_control:
    label: "{{ item }}"
  when: uninstall_kernel_ver is defined

# We use "console serial" so to enable real consoles to be
# preferred first, and fallback to the serial as secondary
# option. This let's us work with hardware serial consoles
# say on IPMIs and virtual guests ('virsh console').
- name: Ensure we can get the GRUB prompt on reboot
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TERMINAL='
    line: GRUB_TERMINAL="console serial"
  tags: [ 'linux', 'git', 'config', 'console' ]

- name: Update your boot GRUB file if necessary
  tags: [ 'linux', 'uninstall-linux', 'manual-update-grub', 'console' ]
  import_tasks: update-grub/main.yml

- name: Ensure we have DEFAULTDEBUG set
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  register: grub_default_saved_cmd
  lineinfile:
    path: /etc/sysconfig/kernel
    regexp: '^DEFAULTDEBUG='
    line: DEFAULTDEBUG=yes
  tags: [ 'linux', 'git', 'config', 'saved' ]
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install {{ target_linux_tree }} on the client side
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{ target_linux_make_install_cmd }}"
  register: install_done
  changed_when: "install_done.rc == 0"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'install-linux' ]

- name: Install {{ target_linux_tree }} cxl_test on the client side
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{ target_linux_make_install_cmd }} M=tools/testing/cxl INSTALL_MOD_DIR=updates"
  register: install_done
  changed_when: "install_done.rc == 0"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'install-linux', 'cxl-install' ]
  when:
    - kdevops_workflow_enable_cxl|bool

- name: Set the default kernel if necessary
  tags: [ 'linux', 'git', 'config', 'saved' ]
  import_tasks: update-grub/install.yml
  # when:
  #   - ansible_facts['os_family']|lower != 'redhat'

- name: Reboot into Linux {{ target_linux_tree }}
  become: yes
  become_method: sudo
  reboot:
  tags: [ 'linux', 'reboot' ]

- name: Run uname
  command: "uname -r"
  register: uname_cmd
  tags: [ 'linux', 'git', 'config', 'uname' ]

- name: Check kernel uname
  debug:
    msg: "Target kernel {{ target_linux_tag }} Running kernel {{ running_kernel }}"
  vars:
    running_kernel: "{{ uname_cmd.stdout_lines.0 }}"
  tags: [ 'linux', 'git', 'config', 'uname' ]
