---
# tasks to install dependencies for pynfs
- name: oscheck distribution ospecific setup
  import_tasks: tasks/install-deps/debian/main.yml
  when: ansible_facts['os_family']|lower == 'debian'
- import_tasks: tasks/install-deps/suse/main.yml
  when: ansible_facts['os_family']|lower == 'suse'
- import_tasks: tasks/install-deps/redhat/main.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Generate /etc/nfs.conf
  tags: [ 'nfsd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  template:
    src: nfs.conf.j2
    dest: /etc/nfs.conf
    owner: root
    group: root
    mode: 0644

- name: Create a new LVM VG
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  community.general.lvg:
    vg: "exports"
    pvs: "{{ nfsd_export_device_0 }},{{ nfsd_export_device_1 }}"

- name: Start up nfsd
  tags: [ 'nfsd' ]
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ansible.builtin.systemd:
    name: nfs-server.service
    enabled: true
    state: reloaded
