---
- name: Install nfsd dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - nfs-common
      - nfs-kernel-server
      - lvm2
    state: present
    update_cache: yes
  tags: [ 'pynfs', 'deps' ]
