---
- name: Install build dependencies for nfstest
  become: yes
  become_method: sudo
  zypper:
    name:
      - gcc
      - git-core
      - make
      - krb5-devel
      - python3.9
      - nfs-utils
    state: present
