---
- name: Install build dependencies for pynfs
  become: yes
  become_method: sudo
  ansible.builtin.package:
    name:
      - gcc
      - git-core
      - make
      - krb5-devel
      - python3-devel
      - swig
      - python3-gssapi
      - python3-ply
    state: present

- name: Install xdrlib3
  ansible.builtin.pip:
    name: xdrlib3
