---
- name: Debian-specific setup
  ansible.builtin.include_tasks: roles/krb5/tasks/install-deps/debian/main.yml
  when: ansible_os_family == 'Debian'

- name: SuSE-specific setup
  ansible.builtin.include_tasks: roles/krb5/tasks/install-deps/suse/main.yml
  when: ansible_os_family == 'Suse'

- name: Red Hat-specific setup
  ansible.builtin.include_tasks: roles/krb5/tasks/install-deps/redhat/main.yml
  when: ansible_os_family == 'RedHat'

- name: Configure /etc/krb5.conf
  become: yes
  become_method: sudo
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure /etc/krb5.conf.d exists
  become: yes
  become_method: sudo
  ansible.builtin.file:
    path: /etc/krb5.conf.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Add nfs principal
  become: yes
  become_method: sudo
  ansible.builtin.shell:
    cmd: kadmin -w {{ krb5_admin_pw }} -q "addprinc -randkey nfs/{{ hostvars[inventory_hostname].ansible_fqdn }}"

- name: Add nfs principal to keytab
  become: yes
  become_method: sudo
  ansible.builtin.shell:
    cmd: kadmin -w {{ krb5_admin_pw }} -q "ktadd -k /etc/krb5.keytab nfs/{{ hostvars[inventory_hostname].ansible_fqdn }}"

- name: Restart rpc.gssd on the NFS server
  become: yes
  become_method: sudo
  delegate_to: "{{ kdevops_hosts_prefix }}-nfsd"
  ansible.builtin.systemd:
    name: rpc-gssd
    state: restarted
